name: style-check

on:
  push:
    branches:
      - '**'

jobs:
  check-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: make install

      - name: Run eslint
        run: make lint
